version: '3.7'
services:
  postgres_db_container:
    image: postgres:13.1-alpine
    container_name: rest_api_db
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres?sslmode=disable
      POSTGRES_USER: marius
      POSTGRES_PASSWORD: magic
      POSTGRES_SSLMODE: disable
    volumes:
      - postgres_data:/var/lib/postgres

volumes:
  postgres_data:
