version: '3.7'
services:
  prometheus:
    image: prom/prometheus:v2.19.0
    volumes:
      - ./etc/prometheus/:/etc/prometheus/
      - ./var/prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
  app:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - prometheus

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - "./var/grafana/grafana_data:/var/lib/grafana"
      - "./etc/grafana/provisioning/:/etc/grafana/provisioning/"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false

  postgres_db_container:
    image: postgres:13.1-alpine
    container_name: rest_api_db
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rest_api_database?sslmode=disable
      POSTGRES_USER: marius
      POSTGRES_PASSWORD: magic
      POSTGRES_SSLMODE: disable
    volumes:
      - postgres_data:/var/lib/postgres

volumes:
  postgres_data:
