version: '3.7'
services:
  postgres_db_container:
    image: postgres:13.1-alpine
    container_name: rest_api_db
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres?sslmode=disable
      POSTGRES_USER: marius
      POSTGRES_PASSWORD: magic
      POSTGRES_SSLMODE: disable
    volumes:
      - postgres_data:/var/lib/postgres

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"

  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

volumes:
  postgres_data:
