// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SalesClient is the client API for Sales service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SalesClient interface {
	GetProductWithHighestSales(ctx context.Context, in *ProductIdRequest, opts ...grpc.CallOption) (*ProductWithSales, error)
	GetSalesForProduct(ctx context.Context, in *ProductIdRequest, opts ...grpc.CallOption) (*Sale, error)
}

type salesClient struct {
	cc grpc.ClientConnInterface
}

func NewSalesClient(cc grpc.ClientConnInterface) SalesClient {
	return &salesClient{cc}
}

func (c *salesClient) GetProductWithHighestSales(ctx context.Context, in *ProductIdRequest, opts ...grpc.CallOption) (*ProductWithSales, error) {
	out := new(ProductWithSales)
	err := c.cc.Invoke(ctx, "/SALES.Sales/GetProductWithHighestSales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *salesClient) GetSalesForProduct(ctx context.Context, in *ProductIdRequest, opts ...grpc.CallOption) (*Sale, error) {
	out := new(Sale)
	err := c.cc.Invoke(ctx, "/SALES.Sales/GetSalesForProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SalesServer is the server API for Sales service.
// All implementations must embed UnimplementedSalesServer
// for forward compatibility
type SalesServer interface {
	GetProductWithHighestSales(context.Context, *ProductIdRequest) (*ProductWithSales, error)
	GetSalesForProduct(context.Context, *ProductIdRequest) (*Sale, error)
	mustEmbedUnimplementedSalesServer()
}

// UnimplementedSalesServer must be embedded to have forward compatible implementations.
type UnimplementedSalesServer struct {
}

func (UnimplementedSalesServer) GetProductWithHighestSales(context.Context, *ProductIdRequest) (*ProductWithSales, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductWithHighestSales not implemented")
}
func (UnimplementedSalesServer) GetSalesForProduct(context.Context, *ProductIdRequest) (*Sale, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSalesForProduct not implemented")
}
func (UnimplementedSalesServer) mustEmbedUnimplementedSalesServer() {}

// UnsafeSalesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SalesServer will
// result in compilation errors.
type UnsafeSalesServer interface {
	mustEmbedUnimplementedSalesServer()
}

func RegisterSalesServer(s grpc.ServiceRegistrar, srv SalesServer) {
	s.RegisterService(&Sales_ServiceDesc, srv)
}

func _Sales_GetProductWithHighestSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalesServer).GetProductWithHighestSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SALES.Sales/GetProductWithHighestSales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalesServer).GetProductWithHighestSales(ctx, req.(*ProductIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sales_GetSalesForProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalesServer).GetSalesForProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SALES.Sales/GetSalesForProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalesServer).GetSalesForProduct(ctx, req.(*ProductIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sales_ServiceDesc is the grpc.ServiceDesc for Sales service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sales_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SALES.Sales",
	HandlerType: (*SalesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductWithHighestSales",
			Handler:    _Sales_GetProductWithHighestSales_Handler,
		},
		{
			MethodName: "GetSalesForProduct",
			Handler:    _Sales_GetSalesForProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "salesservice/proto/sales.proto",
}
